export const mussle = [
  // Грудные
  { title: "upperChest", worth: "upperChest", color: "var(--re)", group: "chest" },
  { title: "middleChest", worth: "middleChest", color: "var(--re)", group: "chest" },
  { title: "lowerChest", worth: "lowerChest", color: "var(--re)", group: "chest" },
  { title: "pectoralisMinor", worth: "pectoralisMinor", color: "var(--re)", group: "chest" },
  { title: "serratusAnterior", worth: "serratusAnterior", color: "var(--re)", group: "chest" },
  { title: "intercostals", worth: "intercostals", color: "var(--re)", group: "chest" },
  // Плечи
  { title: "frontDelts", worth: "frontDelts", color: "var(--re)", group: "shoulders" },
  { title: "sideDelts", worth: "sideDelts", color: "var(--re)", group: "shoulders" },
  { title: "rearDelts", worth: "rearDelts", color: "var(--re)", group: "shoulders" },
  { title: "supraspinatus", worth: "supraspinatus", color: "var(--re)", group: "shoulders" },
  { title: "infraspinatus", worth: "infraspinatus", color: "var(--re)", group: "shoulders" },
  { title: "subscapularis", worth: "subscapularis", color: "var(--re)", group: "shoulders" },
  { title: "teresMajor", worth: "teresMajor", color: "var(--re)", group: "shoulders" },
  { title: "teresMinor", worth: "teresMinor", color: "var(--re)", group: "shoulders" },
  // Руки
  { title: "biceps", worth: "biceps", color: "var(--re)", group: "arms" },
  { title: "brachialis", worth: "brachialis", color: "var(--re)", group: "arms" },
  { title: "tricepsLong", worth: "tricepsLong", color: "var(--re)", group: "arms" },
  { title: "tricepsLateral", worth: "tricepsLateral", color: "var(--re)", group: "arms" },
  { title: "tricepsMedial", worth: "tricepsMedial", color: "var(--re)", group: "arms" },
  { title: "forearmsFlexors", worth: "forearmsFlexors", color: "var(--re)", group: "arms" },
  { title: "forearmsExtensors", worth: "forearmsExtensors", color: "var(--re)", group: "arms" },
  // Спина
  { title: "upperTraps", worth: "upperTraps", color: "var(--re)", group: "back" },
  { title: "middleTraps", worth: "middleTraps", color: "var(--re)", group: "back" },
  { title: "lowerTraps", worth: "lowerTraps", color: "var(--re)", group: "back" },
  { title: "rhomboids", worth: "rhomboids", color: "var(--re)", group: "back" },
  { title: "lats", worth: "lats", color: "var(--re)", group: "back" },
  { title: "erectorSpinae", worth: "erectorSpinae", color: "var(--re)", group: "back" },
  { title: "quadratusLumborum", worth: "quadratusLumborum", color: "var(--re)", group: "back" },
  { title: "levatorScapulae", worth: "levatorScapulae", color: "var(--re)", group: "back" },
  // Пресс
  { title: "rectusAbdominis", worth: "rectusAbdominis", color: "var(--re)", group: "abs" },
  { title: "upperAbs", worth: "upperAbs", color: "var(--re)", group: "abs" },
  { title: "lowerAbs", worth: "lowerAbs", color: "var(--re)", group: "abs" },
  { title: "obliques", worth: "obliques", color: "var(--re)", group: "abs" },
  { title: "transverseAbdominis", worth: "transverseAbdominis", color: "var(--re)", group: "abs" },
  // Ягодицы
  { title: "gluteusMaximus", worth: "gluteusMaximus", color: "var(--re)", group: "glutes" },
  { title: "gluteusMedius", worth: "gluteusMedius", color: "var(--re)", group: "glutes" },
  { title: "gluteusMinimus", worth: "gluteusMinimus", color: "var(--re)", group: "glutes" },
  // Ноги
  { title: "quadriceps", worth: "quadriceps", color: "var(--re)", group: "legs" },
  { title: "vastusMedialis", worth: "vastusMedialis", color: "var(--re)", group: "legs" },
  { title: "vastusLateralis", worth: "vastusLateralis", color: "var(--re)", group: "legs" },
  { title: "vastusIntermedius", worth: "vastusIntermedius", color: "var(--re)", group: "legs" },
  { title: "rectusFemoris", worth: "rectusFemoris", color: "var(--re)", group: "legs" },
  { title: "hamstrings", worth: "hamstrings", color: "var(--re)", group: "legs" },
  { title: "bicepsFemoris", worth: "bicepsFemoris", color: "var(--re)", group: "legs" },
  { title: "semitendinosus", worth: "semitendinosus", color: "var(--re)", group: "legs" },
  { title: "semimembranosus", worth: "semimembranosus", color: "var(--re)", group: "legs" },
  { title: "adductors", worth: "adductors", color: "var(--re)", group: "legs" },
  { title: "gracilis", worth: "gracilis", color: "var(--re)", group: "legs" },
  { title: "pectineus", worth: "pectineus", color: "var(--re)", group: "legs" },
  { title: "hipFlexors", worth: "hipFlexors", color: "var(--re)", group: "legs" },
  { title: "iliopsoas", worth: "iliopsoas", color: "var(--re)", group: "legs" },
  // Икры
  { title: "calves", worth: "calves", color: "var(--re)", group: "calves" },
  { title: "gastrocnemius", worth: "gastrocnemius", color: "var(--re)", group: "calves" },
  { title: "soleus", worth: "soleus", color: "var(--re)", group: "calves" },
  { title: "tibialisAnterior", worth: "tibialisAnterior", color: "var(--re)", group: "calves" },
  // Шея
  { title: "sternocleidomastoid", worth: "sternocleidomastoid", color: "var(--re)", group: "neck" },
  { title: "scalenes", worth: "scalenes", color: "var(--re)", group: "neck" },
  { title: "neckExtensors", worth: "neckExtensors", color: "var(--re)", group: "neck" },
  { title: "neckFlexors", worth: "neckFlexors", color: "var(--re)", group: "neck" },
];
export const mussleGrops = ["chest", "back", "arms", "shoulders", "abs", "glutes", "legs", "calves", "neck"];
